-- script assumes there is...
--      a database called `lake`
--      a user named `lake_admin`
-- and that you have postgis installed!


BEGIN;

GRANT ALL PRIVILEGES ON DATABASE lake TO lake_admin;
ALTER DATABASE lake OWNER TO lake_admin;
CREATE EXTENSION postgis;

CREATE TABLE "Migration" (
	 "id"                    int primary key generated by default as identity,
	 "appliedAt"             timestamp with time zone default current_timestamp,
	 "description"           text
);


CREATE TABLE "Organization" (
	 "id"                    int primary key generated by default as identity,
	 "name"                  text not null unique
);


CREATE TYPE "USER_ROLE"
AS ENUM ( 'ADMIN', 'USER');

CREATE TABLE "User" (
	 "id"                    int primary key generated by default as identity,
	 "name"                  text not null,
	 "email"                 text not null unique,
	 "pilotLicense"          text not null,
	 "role"                  "USER_ROLE" not null default 'USER',

	 "organizationId"        int not null references "Organization"("id")
);

CREATE TABLE "UserAuthentication" (
	 "userId"                      int not null unique references "User"("id"),
	 "password"                    text not null,
	 "loginAttempts"               int default 0,
	 "loginAttemptsExpiresAt"      timestamp not null default (current_timestamp + '1 hour'::interval)

);

CREATE TYPE "DECCO_STATUS"
AS ENUM ( 'OFFLINE', 'STANDBY', 'INITIALIZING', 'INFLIGHT');

CREATE TABLE "Decco" (
	 "id"                  int primary key generated by default as identity,
	 "name"                text not null unique,
	 "status"              "DECCO_STATUS" default 'OFFLINE',
	 "isVirtual"           boolean not null default false,
	 "callsign"            varchar(20) not null,

	 "organizationId"      int not null references "Organization"("id")
);

CREATE TABLE "DeccoAuthentication" (
	 "deccoId"                     int not null unique references "Decco"("id"),
	 "password"                    text not null,
	 "loginAttempts"               int default 0,
	 "loginAttemptsExpiresAt"      timestamp not null default (current_timestamp + '1 hour'::interval)
);


CREATE TABLE "BurnUnit" (
	 "id"                  int primary key generated by default as identity,
	 "createdAt"           timestamp with time zone default current_timestamp,
	 "name"                text not null,

	 "polygon"             geography(polygon),
	 "subpolygons"         geography(polygon),

	 "organizationId"      int not null references "Organization"("id"),
	 "createdById"         int not null references "User"("id")
);

CREATE TABLE "BurnUnitUpdateLog" (
	 "id"                  int primary key generated by default as identity,
	 "createdAt"           timestamp with time zone default current_timestamp,

	 "burnUnitId"          int not null references "BurnUnit"("id"),
	 "userId"              int not null references "User"("id")
);


CREATE TYPE "SURVEY_TYPE"
AS ENUM ( 'PRE', 'PERI', 'POST');

CREATE TABLE "Survey" (
	 "id"                  int primary key generated by default as identity,
	 "type"                "SURVEY_TYPE" not null default 'PRE',

	 "burnUnitId"          int not null references "BurnUnit"("id")
);


CREATE TYPE "FLIGHT_STATUS"
AS ENUM ( 'NOT_STARTED', 'ACTIVE', 'COMPLETE');

CREATE TABLE "Flight" (
	 "id"                  int primary key generated by default as identity,
	 "status"              "FLIGHT_STATUS" default 'NOT_STARTED',
	 "startTime"           timestamp with time zone,
	 "duration"            interval,
	 "endTime"             timestamp with time zone,
	 "path"                geography(linestringm),
	 "subpolygon"          geography(polygon),

	 "deccoId"             int references "Decco"("id"),
	 "pilotId"             int references "User"("id"),
	 "surveyId"            int references "Survey"("id")
);

CREATE TYPE "FLIGHT_EVENT_LEVEL"
AS ENUM ( 'LOW', 'MEDIUM', 'HIGH');

CREATE TYPE "FLIGHT_EVENT_TYPE"
AS ENUM ( 'TASK_STATUS', 'STATE_MACHINE', 'FLIGHT_CONTROL', 'FAILSAFE', 'INFO');

CREATE TABLE "FlightEvent" (
	 "id"                    int primary key generated by default as identity,
	 "acknowledged"          boolean default false,
	 "description"           text,
	 "level"                 "FLIGHT_EVENT_LEVEL" not null,
	 "startTime"             timestamp with time zone,
	 "type"                  "FLIGHT_EVENT_TYPE" not null default('INFO'),
	 "location"              geography(point),

	 "deccoId"              int references "Decco"("id"),
	 "flightId"             int references "Flight"("id")
);

CREATE TABLE "session" (
	 "sid" varchar NOT NULL COLLATE "default",
	 "sess" json NOT NULL,
	 "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

INSERT INTO "Migration" (description)
VALUES ('initialize database');

COMMIT;
