
BEGIN;

CREATE TABLE "ElevationModel" (
  "id"                  int primary key generated by default as identity,
  "url"                 text default null,
  "boundingBox"         geometry(polygon)
);

INSERT INTO "Migration" (description)
VALUES ('Add the `ElevationModel` table');

COMMIT;
