
BEGIN;

-- USER
GRANT ALL PRIVILEGES ON DATABASE lake TO lake_admin;
ALTER DATABASE lake OWNER TO lake_admin;


-- MIGRATIONS
CREATE TABLE migration (
  version               int,
  description           text,
  applied_at            timestamp with time zone default current_timestamp
);


-- ORGANIZATIONS

CREATE TABLE organization (
  id                    bigint primary key generated by default as identity,
  name                  text not null
);


-- PERSONS (aka 'users', which is a reserved word in PostgreSQL)

CREATE TABLE person (
  id                    bigint primary key generated by default as identity,
  email                 text not null,
  password              text not null,
  pilot_license         text not null,

  organization_id       bigint not null references organization(id)
);


-- DECCOS (aka 'drones'!)
-- (enum) decco status

CREATE TYPE decco_status AS ENUM (
  'OFFLINE', 'STANDBY', 'INITIALIZING', 'INFLIGHT'
);

CREATE TABLE decco (
  id                    bigint primary key generated by default as identity,
  name                  text not null,
  password              text not null,
  status                decco_status default 'OFFLINE',
  is_virtual            boolean not null default false,
  remote_id             varchar(20) not null,

  organization_id       bigint not null references organization(id)
);


-- BURN UNITS
-- burn unit update logs

CREATE TABLE burn_unit (
  id                    bigint primary key generated by default as identity,
  created_at            timestamp with time zone default current_timestamp,
  name                  text not null,

  organization_id       bigint not null references organization(id),
  created_by_person_id  bigint not null references person(id)
);

CREATE TABLE burn_unit_update_log (
  id                    bigint primary key generated by default as identity,
  created_at            timestamp with time zone default current_timestamp,

  burn_unit_id          bigint not null references burn_unit(id),
  person_id             bigint not null references person(id)
);


-- SURVEYS
-- (enum) survey types

CREATE TYPE survey_type AS ENUM (
  'PRE', 'PERI', 'POST'
);

CREATE TABLE survey (
  id                    bigint primary key generated by default as identity,
  type                  survey_type not null default 'PRE',

  burn_unit_id          bigint not null references burn_unit(id)
);


-- FLIGHTS
-- flights
-- (enum) flight status
-- flight events
-- (enum) flight event level
-- (enum) flight event type

CREATE TYPE flight_status AS ENUM (
  'NOT_STARTED', 'ACTIVE', 'COMPLETE'
);

CREATE TABLE flight (
  id                    bigint primary key generated by default as identity,
  status                flight_status default 'NOT_STARTED',
  start_time            timestamp with time zone,
  duration              interval,
  end_time              timestamp with time zone,
  -- flight_log
  -- path
  -- subpolygon

  decco_id              bigint references decco(id),
  pilot_id              bigint references person(id)
);

CREATE TYPE flight_event_level AS ENUM (
  'LOW', 'MEDIUM', 'HIGH'
);

CREATE TYPE flight_event_type AS ENUM (
  'TASK_STATUS', 'STATE_MACHINE', 'FLIGHT_CONTROL', 'FAILSAFE', 'INFO'
);

CREATE TABLE flight_event (
  id                    bigint primary key generated by default as identity,
  acknowledged          boolean default false,
  description           text,
  level                 flight_event_level not null,
  start_time            timestamp with time zone,
  type                  flight_event_type not null default('INFO'),
  -- location

  decco_id              bigint references decco(id),
  flight_id             bigint references flight(id)
);


COMMIT;
