
-- we use "timestamp" instead of "bigint" for time tracking
-- https://blog.sql-workbench.eu/post/epoch-mania/

BEGIN;

-- set credentials for `lake_admin` user
GRANT ALL PRIVILEGES ON DATABASE lake TO lake_admin;
ALTER DATABASE lake OWNER TO lake_admin;


-- MIGRATIONS
CREATE TABLE migration (
  version               int,
  description           text,
  applied_at            timestamp with time zone default current_timestamp
);


-- ORGANIZATIONS
CREATE TABLE organization (
  id                    int primary key generated by default as identity,
  name                  text not null unique
);


-- USER_
-- trailing underscore b/c postgres 🤧
CREATE TYPE user_role AS ENUM ( 'ADMIN', 'USER');
CREATE TABLE user_ (
  id                    int primary key generated by default as identity,
  name                  text not null,
  email                 text not null unique,
  pilot_license         text not null,
  role                  user_role not null default 'USER',

  organization_id       int not null references organization(id)
);

CREATE TABLE user_authentication (
  -- one-to-one with user_ so use user_id as unique identifier
  user_id                       int not null unique references user_(id),
  password                      text not null,
  login_attempts                int default 0,
  login_attempts_expires_at     timestamp not null default (current_timestamp + '1 hour'::interval)

);

-- DECCOS (aka 'drones'!)
-- (enum) decco status
CREATE TYPE decco_status AS ENUM (
  'OFFLINE', 'STANDBY', 'INITIALIZING', 'INFLIGHT'
);
CREATE TABLE decco (
  id                    int primary key generated by default as identity,
  name                  text not null unique,
  password              text not null,
  status                decco_status default 'OFFLINE',
  is_virtual            boolean not null default false,
  callsign              varchar(20) not null,

  organization_id       int not null references organization(id)
);

CREATE TABLE decco_authentication (
  -- one-to-one with decco so use decco_id as unique identifier
  decco_id                      int not null unique references decco(id),
  password                      text not null,
  login_attempts                int default 0,
  login_attempts_expires_at     timestamp not null default (current_timestamp + '1 hour'::interval)
);


-- BURN UNITS
-- burn unit update logs

CREATE TABLE burn_unit (
  id                    int primary key generated by default as identity,
  created_at            timestamp with time zone default current_timestamp,
  name                  text not null,

  organization_id       int not null references organization(id),
  created_by_id         int not null references user_(id)
);

CREATE TABLE burn_unit_update_log (
  id                    int primary key generated by default as identity,
  created_at            timestamp with time zone default current_timestamp,

  burn_unit_id          int not null references burn_unit(id),
  user_id               int not null references user_(id)
);


-- SURVEYS
-- (enum) survey types

CREATE TYPE survey_type AS ENUM (
  'PRE', 'PERI', 'POST'
);

CREATE TABLE survey (
  id                    int primary key generated by default as identity,
  type                  survey_type not null default 'PRE',

  burn_unit_id          int not null references burn_unit(id)
);


-- FLIGHTS
-- flights
-- (enum) flight status
-- flight events
-- (enum) flight event level
-- (enum) flight event type

CREATE TYPE flight_status AS ENUM (
  'NOT_STARTED', 'ACTIVE', 'COMPLETE'
);

CREATE TABLE flight (
  id                    int primary key generated by default as identity,
  status                flight_status default 'NOT_STARTED',
  start_time            timestamp with time zone,
  duration              interval,
  end_time              timestamp with time zone,
  path                  geography(linestringm),
  subpolygon            geography(polygon),

  decco_id              int references decco(id),
  pilot_id              int references user_(id),
  survey_id             int references survey(id)
);

CREATE TYPE flight_event_level AS ENUM (
  'LOW', 'MEDIUM', 'HIGH'
);

CREATE TYPE flight_event_type AS ENUM (
  'TASK_STATUS', 'STATE_MACHINE', 'FLIGHT_CONTROL', 'FAILSAFE', 'INFO'
);

CREATE TABLE flight_event (
  id                    int primary key generated by default as identity,
  acknowledged          boolean default false,
  description           text,
  level                 flight_event_level not null,
  start_time            timestamp with time zone,
  type                  flight_event_type not null default('INFO'),
  location              geography(point),

  decco_id              int references decco(id),
  flight_id             int references flight(id)
);


COMMIT;


-- need user to log in
INSERT INTO organization (name) VALUES ('R88');
INSERT INTO user_ (email, name, role, pilot_license, organization_id)
VALUES ('admin@example.com', 'Tyler Lane', 'ADMIN', 'admin000', 1), ('test@example.com', 'Alex McAlex', 'USER',  'test999', 1);

INSERT INTO user_authentication (password, user_id)
VALUES
  ('$argon2id$v=19$m=65536,t=3,p=4$J/QUa5xHKtMf75GXZrl76Q$RiXbKNwiwiakPO0VvVRIXv1KVtqmgh//aT0gMvTtszw', 1),
  ('$argon2id$v=19$m=65536,t=3,p=4$J/QUa5xHKtMf75GXZrl76Q$RiXbKNwiwiakPO0VvVRIXv1KVtqmgh//aT0gMvTtszw', 2);

INSERT INTO decco (name, password, is_virtual, callsign, organization_id)
VALUES
  ('rosy-maple', '$argon2id$v=19$m=65536,t=3,p=4$w8UGwlBJcvyoOtLmh4eEeQ$pUDLDkGqXiG1PSfY4gGdk5BKMfhkTcO4YTZ32bhihYE', true, '#6FD6FF', 1)
