
BEGIN;

-- set credentials for `lake_admin` user
GRANT ALL PRIVILEGES ON DATABASE lake TO lake_admin;
ALTER DATABASE lake OWNER TO lake_admin;


-- MIGRATIONS
CREATE TABLE migration (
  version               int,
  description           text,
  applied_at            timestamp with time zone default current_timestamp
);


-- ORGANIZATIONS
CREATE TABLE organization (
  id                    int primary key generated by default as identity,
  name                  text not null unique
);


-- USER_
-- trailing underscore b/c postgres 🤧
CREATE TABLE user_ (
  id                    int primary key generated by default as identity,
  email                 text not null unique,
  password              text not null,
  pilot_license         text not null,

  organization_id       int not null references organization(id)
);


-- DECCOS (aka 'drones'!)
-- (enum) decco status
CREATE TYPE decco_status AS ENUM (
  'OFFLINE', 'STANDBY', 'INITIALIZING', 'INFLIGHT'
);
CREATE TABLE decco (
  id                    int primary key generated by default as identity,
  name                  text not null unique,
  password              text not null,
  status                decco_status default 'OFFLINE',
  is_virtual            boolean not null default false,
  callsign              varchar(20) not null,

  organization_id       int not null references organization(id)
);


-- BURN UNITS
-- burn unit update logs

CREATE TABLE burn_unit (
  id                    int primary key generated by default as identity,
  created_at            timestamp with time zone default current_timestamp,
  name                  text not null,

  organization_id       int not null references organization(id),
  created_by_id         int not null references user_(id)
);

CREATE TABLE burn_unit_update_log (
  id                    int primary key generated by default as identity,
  created_at            timestamp with time zone default current_timestamp,

  burn_unit_id          int not null references burn_unit(id),
  user_id               int not null references user_(id)
);


-- SURVEYS
-- (enum) survey types

CREATE TYPE survey_type AS ENUM (
  'PRE', 'PERI', 'POST'
);

CREATE TABLE survey (
  id                    int primary key generated by default as identity,
  type                  survey_type not null default 'PRE',

  burn_unit_id          int not null references burn_unit(id)
);


-- FLIGHTS
-- flights
-- (enum) flight status
-- flight events
-- (enum) flight event level
-- (enum) flight event type

CREATE TYPE flight_status AS ENUM (
  'NOT_STARTED', 'ACTIVE', 'COMPLETE'
);

CREATE TABLE flight (
  id                    int primary key generated by default as identity,
  status                flight_status default 'NOT_STARTED',
  start_time            timestamp with time zone,
  duration              interval,
  end_time              timestamp with time zone,
  path                  geography(linestringm),
  subpolygon            geography(polygon),

  decco_id              int references decco(id),
  pilot_id              int references user_(id),
  survey_id             int references survey(id)
);

CREATE TYPE flight_event_level AS ENUM (
  'LOW', 'MEDIUM', 'HIGH'
);

CREATE TYPE flight_event_type AS ENUM (
  'TASK_STATUS', 'STATE_MACHINE', 'FLIGHT_CONTROL', 'FAILSAFE', 'INFO'
);

CREATE TABLE flight_event (
  id                    int primary key generated by default as identity,
  acknowledged          boolean default false,
  description           text,
  level                 flight_event_level not null,
  start_time            timestamp with time zone,
  type                  flight_event_type not null default('INFO'),
  location              geography(point),

  decco_id              int references decco(id),
  flight_id             int references flight(id)
);


COMMIT;
