
-- we use "timestamp" instead of "bigint" for time tracking
-- https://blog.sql-workbench.eu/post/epoch-mania/

-- conventions, all singular:
--      - TableName
--      - columnName
--      - ENUM_NAME
--      - user_name, database_name (no quotes)
--
-- we're stuck putting quotes around everything b/c I want to use camelCase in JavaScript
-- and I don't want to have the overhead of a conversion layer

BEGIN;

-- set credentials for `lake_admin` user
GRANT ALL PRIVILEGES ON DATABASE lake TO lake_admin;
ALTER DATABASE lake OWNER TO lake_admin;


-- MIGRATIONS
CREATE TABLE "Migration" (
  "version"               int,
  "description"           text,
  "appliedAt"             timestamp with time zone default current_timestamp
);


-- ORGANIZATIONS
CREATE TABLE "Organization" (
  "id"                    int primary key generated by default as identity,
  "name"                  text not null unique
);


-- USER
CREATE TYPE "USER_ROLE"
AS ENUM ( 'ADMIN', 'USER');

CREATE TABLE "User" (
  "id"                    int primary key generated by default as identity,
  "name"                  text not null,
  "email"                 text not null unique,
  "pilotLicense"          text not null,
  "role"                  "USER_ROLE" not null default 'USER',

  "organizationId"        int not null references "Organization"("id")
);

CREATE TABLE "UserAuthentication" (
  -- one-to-one with user_ so use user_id as unique identifier
  "userId"                      int not null unique references "User"("id"),
  "password"                    text not null,
  "loginAttempts"               int default 0,
  "loginAttemptsExpiresAt"      timestamp not null default (current_timestamp + '1 hour'::interval)

);

-- DECCOS (aka 'drones'!)
-- (enum) decco status
CREATE TYPE "DECCO_STATUS"
AS ENUM ( 'OFFLINE', 'STANDBY', 'INITIALIZING', 'INFLIGHT');

CREATE TABLE "Decco" (
  "id"                  int primary key generated by default as identity,
  "name"                text not null unique,
  "password"            text not null,
  "status"              "DECCO_STATUS" default 'OFFLINE',
  "isVirtual"           boolean not null default false,
  "callsign"            varchar(20) not null,

  "organizationId"      int not null references "Organization"("id")
);

CREATE TABLE "DeccoAuthentication" (
  -- one-to-one with Decco so use deccoId as the unique id
  "deccoId"                     int not null unique references "Decco"("id"),
  "password"                    text not null,
  "loginAttempts"               int default 0,
  "loginAttemptsExpiresAt"      timestamp not null default (current_timestamp + '1 hour'::interval)
);


-- BURN UNITS
-- burn unit update logs

CREATE TABLE "BurnUnit" (
  "id"                  int primary key generated by default as identity,
  "createdAt"           timestamp with time zone default current_timestamp,
  "name"                text not null,

  "organizationId"      int not null references "Organization"("id"),
  "createdById"         int not null references "User"("id")
);

CREATE TABLE "BurnUnitUpdateLog" (
  "id"                  int primary key generated by default as identity,
  "createdAt"           timestamp with time zone default current_timestamp,

  "burnUnitId"          int not null references "BurnUnit"("id"),
  "userId"              int not null references "User"("id")
);


-- SURVEYS
-- (enum) survey types

CREATE TYPE "SURVEY_TYPE"
AS ENUM ( 'PRE', 'PERI', 'POST');

CREATE TABLE "Survey" (
  "id"                  int primary key generated by default as identity,
  "type"                "SURVEY_TYPE" not null default 'PRE',

  "burnUnitId"          int not null references "BurnUnit"("id")
);


-- FLIGHTS
-- flights
-- (enum) flight status
-- flight events
-- (enum) flight event level
-- (enum) flight event type

CREATE TYPE "FLIGHT_STATUS"
AS ENUM ( 'NOT_STARTED', 'ACTIVE', 'COMPLETE');

CREATE TABLE "Flight" (
  "id"                  int primary key generated by default as identity,
  "status"              "FLIGHT_STATUS" default 'NOT_STARTED',
  "startTime"           timestamp with time zone,
  "duration"            interval,
  "endTime"             timestamp with time zone,
  "path"                geography(linestringm),
  "subpolygon"          geography(polygon),

  "deccoId"             int references "Decco"("id"),
  "pilotId"             int references "User"("id"),
  "surveyId"            int references "Survey"("id")
);

CREATE TYPE "FLIGHT_EVENT_LEVEL"
AS ENUM ( 'LOW', 'MEDIUM', 'HIGH');

CREATE TYPE "FLIGHT_EVENT_TYPE"
AS ENUM ( 'TASK_STATUS', 'STATE_MACHINE', 'FLIGHT_CONTROL', 'FAILSAFE', 'INFO');

CREATE TABLE "FlightEvent" (
  "id"                    int primary key generated by default as identity,
  "acknowledged"          boolean default false,
  "description"           text,
  "level"                 "FLIGHT_EVENT_LEVEL" not null,
  "startTime"             timestamp with time zone,
  "type"                  "FLIGHT_EVENT_TYPE" not null default('INFO'),
  "location"              geography(point),

  "deccoId"              int references "Decco"("id"),
  "flightId"             int references "Flight"("id")
);


COMMIT;


-- need users to log in!
INSERT INTO "Organization" (name)
VALUES ('R88');

INSERT INTO "User" (email, name, role, "pilotLicense", "organizationId") VALUES
('admin@example.com', 'Tyler Lane',  'ADMIN', 'admin000', 1),
('test@example.com',  'Alex McAlex', 'USER',  'test999',  1);

INSERT INTO "UserAuthentication" (password, "userId") VALUES
('$argon2id$v=19$m=65536,t=3,p=4$J/QUa5xHKtMf75GXZrl76Q$RiXbKNwiwiakPO0VvVRIXv1KVtqmgh//aT0gMvTtszw', 1),
('$argon2id$v=19$m=65536,t=3,p=4$J/QUa5xHKtMf75GXZrl76Q$RiXbKNwiwiakPO0VvVRIXv1KVtqmgh//aT0gMvTtszw', 2);

INSERT INTO "Decco" (name, password, "isVirtual", callsign, "organizationId") VALUES
('rosy-maple', '$argon2id$v=19$m=65536,t=3,p=4$w8UGwlBJcvyoOtLmh4eEeQ$pUDLDkGqXiG1PSfY4gGdk5BKMfhkTcO4YTZ32bhihYE', true, '#6FD6FF', 1)
