-- LOGGING
CREATE TABLE "RequestLog" (
  "id"                  int primary key generated by default as identity,
  "userId"              int references "User"(id),
  "organizationId"      int references "Organization"(id),
  "timestamp"           timestamp with time zone default current_timestamp,

  "ip"                  text,
  "method"              text,
  "endpoint"            text
);

